core_shop_payment:
    pimcore_admin:
        js:
            resource: '/bundles/coreshoppayment/pimcore/js/resource.js'
            payment_item: '/bundles/coreshoppayment/pimcore/js/provider/item.js'
            payment_panel: '/bundles/coreshoppayment/pimcore/js/provider/panel.js'
            payment_gateway_abstract: '/bundles/coreshoppayment/pimcore/js/provider/gateways/abstract.js'
            payment_gateway_paypal: '/bundles/coreshoppayment/pimcore/js/provider/gateways/paypal_express_checkout.js'
            payment_gateway_sofort: '/bundles/coreshoppayment/pimcore/js/provider/gateways/sofort.js'
            payment_provider_rule_item: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/item.js'
            payment_provider_rule_panel: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/panel.js'
            payment_provider_rule_action: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/action.js'
            payment_provider_rule_condition: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/condition.js'
            payment_provider_rule_actions_addition_percent: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/actions/additionPercent.js'
            payment_provider_rule_actions_discount_percent: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/actions/discountPercent.js'
            payment_provider_rule_actions_payment_provider_rule: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/actions/paymentProviderRule.js'
            payment_provider_rule_conditions_amount: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/amount.js'
            payment_provider_rule_conditions_dimension: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/dimension.js'
            payment_provider_rule_conditions_nested: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/nested.js'
            payment_provider_rule_conditions_postcodes: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/postcodes.js'
            payment_provider_rule_conditions_shippingRule: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/paymentProviderRule.js'
            payment_provider_rule_conditions_weight: '/bundles/coreshoppayment/pimcore/js/paymentproviderrule/conditions/weight.js'
            core_extension_data_provider: '/bundles/coreshoppayment/pimcore/js/coreExtension/data/coreShopPaymentProvider.js'
            core_extension_tag_provider: '/bundles/coreshoppayment/pimcore/js/coreExtension/tags/coreShopPaymentProvider.js'
            core_extension_data_provider_multiselect: '/bundles/coreshoppayment/pimcore/js/coreExtension/data/coreShopPaymentProviderMultiselect.js'
            core_extension_tag_provider_multiselect: '/bundles/coreshoppayment/pimcore/js/coreExtension/tags/coreShopPaymentProviderMultiselect.js'
        css:
            payment: '/bundles/coreshoppayment/pimcore/css/payment.css'
        editmode_js:
            core_extension_document_tag_provider: '/bundles/coreshoppayment/pimcore/js/coreExtension/document/coreShopPaymentProvider.js'
